table Reseller
	lineageTag: 98b5c3c0-b491-4d6b-9129-e469911af810

	column ResellerKey
		dataType: int64
		formatString: 0
		lineageTag: 18a1aaf9-093e-45d1-b775-08b61ac552bd
		summarizeBy: count
		sourceColumn: ResellerKey

		annotation SummarizationSetBy = Automatic

	column 'Reseller ID'
		dataType: string
		lineageTag: 05046215-d034-452b-a26c-ddb58bbe5a90
		summarizeBy: none
		sourceColumn: Reseller ID

		annotation SummarizationSetBy = Automatic

	column 'Business Type'
		dataType: string
		lineageTag: 145fb452-c153-496b-96a8-c902addc7e5e
		summarizeBy: none
		sourceColumn: Business Type

		annotation SummarizationSetBy = Automatic

	column Reseller
		dataType: string
		lineageTag: 72fb99ae-1ffd-4b74-aa3b-3e5f1e48dc4f
		summarizeBy: none
		sourceColumn: Reseller

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: d131b6c8-df28-4617-8288-0e9e3104742b
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column State-Province
		dataType: string
		lineageTag: a2a7a18a-1b53-42c8-952e-de63a67982d6
		summarizeBy: none
		sourceColumn: State-Province

		annotation SummarizationSetBy = Automatic

	column Country-Region
		dataType: string
		lineageTag: 0992a03c-317d-4579-9019-2bbab6c05fd3
		summarizeBy: none
		sourceColumn: Country-Region

		annotation SummarizationSetBy = Automatic

	column 'Postal Code'
		dataType: string
		lineageTag: 571b4024-70e1-4f09-a75c-af180768addf
		summarizeBy: none
		sourceColumn: Postal Code

		annotation SummarizationSetBy = Automatic

	partition Reseller = m
		mode: import
		source =
				let
				     Source = Excel.Workbook(File.Contents("D:\AdventureWorks Sales.xlsx"), null, true),
				    Reseller_Table = Source{[Item="Reseller",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(Reseller_Table,{{"ResellerKey", Int64.Type}, {"Reseller ID", type text}, {"Business Type", type text}, {"Reseller", type text}, {"City", type text}, {"State-Province", type text}, {"Country-Region", type text}, {"Postal Code", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

